version: '3.8'

services:
  grpc_server:
    image: ${DOCKER_USERNAME}/grpc_server:${COMMON_IMAGES_VERSION}
    ports:
      - "50051:50051"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "grpc_health_probe -addr=:50051 || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 15
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G

  test_runner:
    image: ${DOCKER_USERNAME}/cwbot_base:${COMMON_IMAGES_VERSION}
    entrypoint: []  # Явный сброс entrypoint
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GRPC_SERVER_ADDRESS=grpc_server:50051
      - MESSAGES_FILE_PATH=./bins/Tests/FunctionalTests/CursedWordsTest/messages.txt
      - SOURCE_DIR=${SOURCE_DIR}
    depends_on:
      grpc_server:
        condition: service_healthy
    volumes:
    - ${SOURCE_DIR}:/app:cached  # Явно указываем режим монтирования
    working_dir: /app
    command:
    - /bin/bash
    - -c
    - |
      /app/bins/Tests/FunctionalTests/CursedWordsTest/cursedWordsTest
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
