name: CursedWords Bot CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: docker.io/jonnyrembo/cwbot_base:1.0
      env:
        TELEGRAM_BOT_TOKEN: "-token 7763682966:AAEFBGifblSqB5of8cyS5WKjC6kK6pxTIuY"
        DOCKER_USERNAME: "jonnyrembo"
        COMMON_IMAGES_VERSION: "1.0"
        TARGET_IMAGES_VERSION: "1.0"
        SOURCE_DIR: ${{ github.workspace }}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${{ github.workspace }}:/github/workspace  # Монтируем в стандартный путь
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          ./build-local.sh

      - name: Run all unit tests
        run: |
          cd build
          ctest --output-on-failure --verbose


      - name: Start infrastructure and run functional tests
        run: |
          ./functional_tests_enviroment.sh up
          ./docker-compose-run-tests.sh
          ./functional_tests_enviroment.sh down